# Generated by Django 3.0 on 2020-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200126_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='namesong1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='namesong2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='namesong3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
