# Generated by Django 3.0 on 2020-01-26 08:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200126_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='song1',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Profile.upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='song2',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Profile.upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='song3',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Profile.upload_to),
        ),
    ]
