# Generated by Django 3.0.3 on 2020-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200126_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='song1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='song2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='song3',
        ),
        migrations.AddField(
            model_name='profile',
            name='urlsong1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='urlsong2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='urlsong3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
