# Generated by Django 3.0.3 on 2020-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200225_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('pop', 'POP'), ('rock', 'ROCK'), ('salsa', 'SALSA'), ('urbano', 'URBANO'), ('popular', 'POPULAR'), ('son cubano', 'SON CUBANO')], default='pop', max_length=15),
        ),
    ]
